stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main

deploy:
  stage: deploy
  tags:
    - home-runner # Pastikan tag ini sesuai dengan tag runner lokal Anda
  before_script:
    - cp $ENV_FILE .env
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker stop nextjs-app || true
    - docker rm nextjs-app || true
    - docker run -d --name nextjs-app -p 3000:3000 --restart unless-stopped $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main
